/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cnvert;

/**
 *
 * @author Abdessamed
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        temperatures.setVisible(false);
        volume.setVisible(false);
        masse.setVisible(false);
        distance.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home = new javax.swing.JPanel();
        tm = new javax.swing.JButton();
        vol = new javax.swing.JButton();
        mas = new javax.swing.JButton();
        dis = new javax.swing.JButton();
        ex = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        temperatures = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        conv_t = new javax.swing.JButton();
        clc_t = new javax.swing.JButton();
        comb_t = new javax.swing.JComboBox<>();
        back_t = new javax.swing.JButton();
        ex_t = new javax.swing.JButton();
        input_t = new javax.swing.JTextField();
        output_t = new javax.swing.JTextField();
        titel_t = new javax.swing.JLabel();
        volume = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        conv_v = new javax.swing.JButton();
        clc_v = new javax.swing.JButton();
        comb_v = new javax.swing.JComboBox<>();
        back_v = new javax.swing.JButton();
        ex_v = new javax.swing.JButton();
        input_v = new javax.swing.JTextField();
        output_v = new javax.swing.JTextField();
        titel_v = new javax.swing.JLabel();
        masse = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        conv_m = new javax.swing.JButton();
        clc_m = new javax.swing.JButton();
        comb_m = new javax.swing.JComboBox<>();
        back_m = new javax.swing.JButton();
        ex_m = new javax.swing.JButton();
        input_m = new javax.swing.JTextField();
        output_m = new javax.swing.JTextField();
        titel_m = new javax.swing.JLabel();
        distance = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        conv_d = new javax.swing.JButton();
        clc_d = new javax.swing.JButton();
        comb_d = new javax.swing.JComboBox<>();
        back_d = new javax.swing.JButton();
        ex_d = new javax.swing.JButton();
        input_d = new javax.swing.JTextField();
        output_d = new javax.swing.JTextField();
        titel_d = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(0, 153, 153));
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tm.setBackground(new java.awt.Color(255, 153, 0));
        tm.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        tm.setText("Températures");
        tm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmActionPerformed(evt);
            }
        });
        home.add(tm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 170, 100));

        vol.setBackground(new java.awt.Color(255, 255, 51));
        vol.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        vol.setText("Volume");
        vol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volActionPerformed(evt);
            }
        });
        home.add(vol, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 170, 100));

        mas.setBackground(new java.awt.Color(51, 204, 255));
        mas.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        mas.setText("Masse");
        mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masActionPerformed(evt);
            }
        });
        home.add(mas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 170, 100));

        dis.setBackground(new java.awt.Color(102, 255, 102));
        dis.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        dis.setText("Distance");
        dis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disActionPerformed(evt);
            }
        });
        home.add(dis, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 170, 100));

        ex.setBackground(new java.awt.Color(255, 0, 0));
        ex.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        ex.setText("Exit");
        ex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exActionPerformed(evt);
            }
        });
        home.add(ex, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 100, 50));

        jLabel4.setFont(new java.awt.Font("MingLiU-ExtB", 1, 48)); // NOI18N
        jLabel4.setText("convertuer");
        home.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 380));

        this.getRootPane().setDefaultButton(conv_t);
        conv_t.requestFocus();
        temperatures.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setText("Températures");

        jLabel2.setText("Resulte");

        conv_t.setText("convert");
        conv_t.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conv_tMouseClicked(evt);
            }
        });
        conv_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conv_tActionPerformed(evt);
            }
        });

        clc_t.setText("clear");
        clc_t.setEnabled(false);
        clc_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clc_tActionPerformed(evt);
            }
        });

        comb_t.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C → F", "C → K", "F → C", "K → C" }));

        back_t.setText("Back");
        back_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_tActionPerformed(evt);
            }
        });

        ex_t.setBackground(new java.awt.Color(255, 0, 0));
        ex_t.setText("Exit");
        ex_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ex_tActionPerformed(evt);
            }
        });

        input_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_tActionPerformed(evt);
            }
        });
        input_t.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                input_tKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input_tKeyReleased(evt);
            }
        });

        output_t.setEnabled(false);

        titel_t.setFont(new java.awt.Font("MingLiU-ExtB", 0, 24)); // NOI18N
        titel_t.setText("Températures");

        javax.swing.GroupLayout temperaturesLayout = new javax.swing.GroupLayout(temperatures);
        temperatures.setLayout(temperaturesLayout);
        temperaturesLayout.setHorizontalGroup(
            temperaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, temperaturesLayout.createSequentialGroup()
                .addGroup(temperaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(temperaturesLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(back_t, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ex_t))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, temperaturesLayout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(output_t, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
            .addGroup(temperaturesLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(temperaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(conv_t, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(temperaturesLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(input_t, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94)
                .addComponent(clc_t, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, temperaturesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titel_t)
                .addGap(226, 226, 226))
            .addGroup(temperaturesLayout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(comb_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        temperaturesLayout.setVerticalGroup(
            temperaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(temperaturesLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(titel_t)
                .addGap(38, 38, 38)
                .addGroup(temperaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_t, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(output_t, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(comb_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(temperaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clc_t, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conv_t, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(temperaturesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ex_t, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(back_t, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );

        getContentPane().add(temperatures, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 380));

        this.getRootPane().setDefaultButton(conv_v);
        conv_v.requestFocus();
        volume.setBackground(new java.awt.Color(255, 255, 51));

        jLabel3.setText("Volume");

        jLabel5.setText("Resulte");

        conv_v.setText("convert");
        conv_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conv_vActionPerformed(evt);
            }
        });

        clc_v.setText("clear");
        clc_v.setEnabled(false);
        clc_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clc_vActionPerformed(evt);
            }
        });

        comb_v.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L → M3", "L → Gallon", "M3 → L", "Gallon → L" }));

        back_v.setText("Back");
        back_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_vActionPerformed(evt);
            }
        });

        ex_v.setBackground(new java.awt.Color(255, 0, 0));
        ex_v.setText("Exit");
        ex_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ex_vActionPerformed(evt);
            }
        });

        input_v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_vActionPerformed(evt);
            }
        });
        input_v.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                input_vKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input_vKeyReleased(evt);
            }
        });

        output_v.setEnabled(false);

        titel_v.setFont(new java.awt.Font("MingLiU-ExtB", 0, 24)); // NOI18N
        titel_v.setText("Volume");

        javax.swing.GroupLayout volumeLayout = new javax.swing.GroupLayout(volume);
        volume.setLayout(volumeLayout);
        volumeLayout.setHorizontalGroup(
            volumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, volumeLayout.createSequentialGroup()
                .addGroup(volumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(volumeLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(back_v, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ex_v))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, volumeLayout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(output_v, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
            .addGroup(volumeLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(volumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(conv_v, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(volumeLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(input_v, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94)
                .addComponent(clc_v, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(volumeLayout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addGroup(volumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titel_v)
                    .addComponent(comb_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        volumeLayout.setVerticalGroup(
            volumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(volumeLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(titel_v)
                .addGap(39, 39, 39)
                .addGroup(volumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_v, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(output_v, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(comb_v, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(volumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clc_v, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conv_v, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(volumeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ex_v, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(back_v, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );

        getContentPane().add(volume, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 380));

        this.getRootPane().setDefaultButton(conv_m);
        conv_m.requestFocus();
        masse.setBackground(new java.awt.Color(51, 204, 255));

        jLabel6.setText("Masse");

        jLabel7.setText("Resulte");

        conv_m.setText("convert");
        conv_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conv_mActionPerformed(evt);
            }
        });

        clc_m.setText("clear");
        clc_m.setEnabled(false);
        clc_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clc_mActionPerformed(evt);
            }
        });

        comb_m.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tonne → Kg", "Pound → Kg", "Kg → Tonne", "Kg → Pound" }));

        back_m.setText("Back");
        back_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_mActionPerformed(evt);
            }
        });

        ex_m.setBackground(new java.awt.Color(255, 0, 0));
        ex_m.setText("Exit");
        ex_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ex_mActionPerformed(evt);
            }
        });

        input_m.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                input_mKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input_mKeyReleased(evt);
            }
        });

        output_m.setEnabled(false);

        titel_m.setFont(new java.awt.Font("MingLiU-ExtB", 0, 24)); // NOI18N
        titel_m.setText("Masse");

        javax.swing.GroupLayout masseLayout = new javax.swing.GroupLayout(masse);
        masse.setLayout(masseLayout);
        masseLayout.setHorizontalGroup(
            masseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, masseLayout.createSequentialGroup()
                .addGroup(masseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(masseLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(back_m, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ex_m))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, masseLayout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(output_m, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
            .addGroup(masseLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(masseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(conv_m, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(masseLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(input_m, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94)
                .addComponent(clc_m, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(masseLayout.createSequentialGroup()
                .addGroup(masseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(masseLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(titel_m))
                    .addGroup(masseLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(comb_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        masseLayout.setVerticalGroup(
            masseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masseLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(titel_m)
                .addGap(34, 34, 34)
                .addGroup(masseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_m, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(output_m, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(comb_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(masseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clc_m, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conv_m, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(masseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ex_m, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(back_m, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );

        getContentPane().add(masse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 380));

        this.getRootPane().setDefaultButton(conv_d);
        conv_d.requestFocus();
        distance.setBackground(new java.awt.Color(102, 255, 102));

        jLabel8.setText("Distance");

        jLabel9.setText("Resulte");

        conv_d.setText("convert");
        conv_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conv_dActionPerformed(evt);
            }
        });
        conv_d.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                conv_dKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                conv_dKeyReleased(evt);
            }
        });

        clc_d.setText("clear");
        clc_d.setEnabled(false);
        clc_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clc_dActionPerformed(evt);
            }
        });

        comb_d.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M → inch", "Yard → M", "Mile → Km", "M → foot" }));

        back_d.setText("Back");
        back_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_dActionPerformed(evt);
            }
        });

        ex_d.setBackground(new java.awt.Color(255, 0, 0));
        ex_d.setText("Exit");
        ex_d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ex_dActionPerformed(evt);
            }
        });

        input_d.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                input_dKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input_dKeyReleased(evt);
            }
        });

        output_d.setEnabled(false);

        titel_d.setFont(new java.awt.Font("MingLiU-ExtB", 0, 24)); // NOI18N
        titel_d.setText("Distance");

        javax.swing.GroupLayout distanceLayout = new javax.swing.GroupLayout(distance);
        distance.setLayout(distanceLayout);
        distanceLayout.setHorizontalGroup(
            distanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, distanceLayout.createSequentialGroup()
                .addGroup(distanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(distanceLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(back_d, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ex_d))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, distanceLayout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(output_d, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
            .addGroup(distanceLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(distanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(conv_d, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(distanceLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(input_d, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94)
                .addComponent(clc_d, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, distanceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titel_d)
                .addGap(226, 226, 226))
            .addGroup(distanceLayout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(comb_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        distanceLayout.setVerticalGroup(
            distanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(distanceLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(titel_d)
                .addGap(38, 38, 38)
                .addGroup(distanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input_d, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(output_d, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(comb_d, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(distanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clc_d, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(conv_d, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(distanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ex_d, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(back_d, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );

        getContentPane().add(distance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 380));

        setSize(new java.awt.Dimension(614, 409));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmActionPerformed
        // TODO add your handling code here:
        home.setVisible(false);
        temperatures.setVisible(true);
        volume.setVisible(false);
        masse.setVisible(false);
        distance.setVisible(false);
    }//GEN-LAST:event_tmActionPerformed

    private void ex_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ex_tActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ex_tActionPerformed

    private void exActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exActionPerformed

    private void masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masActionPerformed
        // TODO add your handling code here:
        home.setVisible(false);
        temperatures.setVisible(false);
        volume.setVisible(false);
        masse.setVisible(true);
        distance.setVisible(false);
    }//GEN-LAST:event_masActionPerformed

    private void back_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_tActionPerformed
        // TODO add your handling code here:
        home.setVisible(true);
        temperatures.setVisible(false);
        volume.setVisible(false);
        masse.setVisible(false);
        distance.setVisible(false);
    }//GEN-LAST:event_back_tActionPerformed

    private void conv_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conv_tActionPerformed
        // TODO add your handling code here:

        double inputt=Double.parseDouble(input_t.getText());
        int chooset=comb_t.getSelectedIndex();
        double outputt=0;
        switch (chooset){
            case 0:outputt=inputt*0;
            break;
            case 1:outputt=inputt*0;
            break;
            case 2:outputt=inputt*0;
            break;
            case 3:outputt=inputt*0;
            break;
        }
        output_t.setText(String.valueOf(outputt));
    }//GEN-LAST:event_conv_tActionPerformed

    private void clc_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clc_tActionPerformed
        // TODO add your handling code here:
        input_t.setText("");
        output_t.setText("");
        clc_t.setEnabled(false);
        conv_t.requestFocus();
    }//GEN-LAST:event_clc_tActionPerformed

    private void input_tKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_tKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER){
            conv_t.doClick();
        }
    }//GEN-LAST:event_input_tKeyPressed

    private void input_tKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_tKeyReleased
        // TODO add your handling code here:
        if(input_t.getText().isEmpty()){
            clc_t.setEnabled(false);
        }
        else {
            clc_t.setEnabled(true);
        }
    }//GEN-LAST:event_input_tKeyReleased

    private void conv_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conv_vActionPerformed
        // TODO add your handling code here:
        double inputv=Double.parseDouble(input_v.getText());
        int choosev=comb_v.getSelectedIndex();
        double outputv=0;
        switch (choosev){
            case 0:outputv=inputv*0;
            break;
            case 1:outputv=inputv*0;
            break;
            case 2:outputv=inputv*0;
            break;
            case 3:outputv=inputv*0;
            break;
        }
        output_v.setText(String.valueOf(outputv));
    
        
    }//GEN-LAST:event_conv_vActionPerformed

    private void clc_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clc_vActionPerformed
        // TODO add your handling code here:
        input_v.setText("");
        output_v.setText("");
        clc_v.setEnabled(false);
        conv_v.requestFocus();
    }//GEN-LAST:event_clc_vActionPerformed

    private void back_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_vActionPerformed
        // TODO add your handling code here:
        home.setVisible(true);
        temperatures.setVisible(false);
        volume.setVisible(false);
        masse.setVisible(false);
        distance.setVisible(false);
    }//GEN-LAST:event_back_vActionPerformed

    private void ex_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ex_vActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ex_vActionPerformed

    private void input_vKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_vKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER){
            conv_v.doClick();
        }
    }//GEN-LAST:event_input_vKeyPressed

    private void input_vKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_vKeyReleased
        // TODO add your handling code here:
        if(input_v.getText().isEmpty()){
            clc_v.setEnabled(false);
        }
        else {
            clc_v.setEnabled(true);
        }
    }//GEN-LAST:event_input_vKeyReleased

    private void conv_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conv_mActionPerformed
        // TODO add your handling code here:
        double inputm=Double.parseDouble(input_m.getText());
        int choosem=comb_m.getSelectedIndex();
        double outputm=0;
        switch (choosem){
            case 0:outputm=inputm*0;
            break;
            case 1:outputm=inputm*0;
            break;
            case 2:outputm=inputm*0;
            break;
            case 3:outputm=inputm*0;
            break;
        }
        output_m.setText(String.valueOf(outputm));
    }//GEN-LAST:event_conv_mActionPerformed

    private void clc_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clc_mActionPerformed
        // TODO add your handling code here:
        input_m.setText("");
        output_m.setText("");
        clc_m.setEnabled(false);
        conv_m.requestFocus();
    }//GEN-LAST:event_clc_mActionPerformed

    private void back_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_mActionPerformed
        // TODO add your handling code here:
        home.setVisible(true);
        temperatures.setVisible(false);
        volume.setVisible(false);
        masse.setVisible(false);
        distance.setVisible(false);
    }//GEN-LAST:event_back_mActionPerformed

    private void ex_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ex_mActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ex_mActionPerformed

    private void input_mKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_mKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER){
            conv_m.doClick();
        }
    }//GEN-LAST:event_input_mKeyPressed

    private void input_mKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_mKeyReleased
        // TODO add your handling code here:
        if(input_m.getText().isEmpty()){
            clc_m.setEnabled(false);
        }
        else {
            clc_m.setEnabled(true);
        }
    }//GEN-LAST:event_input_mKeyReleased

    private void conv_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conv_dActionPerformed
        // TODO add your handling code here:
        double inputd=Double.parseDouble(input_d.getText());
        int choosed=comb_d.getSelectedIndex();
        double outputd=0;
        switch (choosed){
            case 0:outputd=inputd*39.3701;
            break;
            case 1:outputd=inputd*0.9144;
            break;
            case 2:outputd=inputd*1.609;
            break;
            case 3:outputd=inputd*3.2809;
            break;
        }
        output_d.setText(String.valueOf(outputd));
    }//GEN-LAST:event_conv_dActionPerformed

    private void clc_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clc_dActionPerformed
        // TODO add your handling code here:
        input_d.setText("");
        output_d.setText("");
        clc_d.setEnabled(false);
        conv_d.requestFocus();
    }//GEN-LAST:event_clc_dActionPerformed

    private void back_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_dActionPerformed
        // TODO add your handling code here:
        home.setVisible(true);
        temperatures.setVisible(false);
        volume.setVisible(false);
        masse.setVisible(false);
        distance.setVisible(false);
    }//GEN-LAST:event_back_dActionPerformed

    private void ex_dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ex_dActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ex_dActionPerformed

    private void input_dKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_dKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==evt.VK_ENTER){
            conv_d.doClick();
        }
    }//GEN-LAST:event_input_dKeyPressed

    private void input_dKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_dKeyReleased
        // TODO add your handling code here:
        if(input_d.getText().isEmpty()){
            clc_d.setEnabled(false);
        }
        else {
            clc_d.setEnabled(true);
        }
    }//GEN-LAST:event_input_dKeyReleased

    private void volActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volActionPerformed
        // TODO add your handling code here:
        home.setVisible(false);
        temperatures.setVisible(false);
        volume.setVisible(true);
        masse.setVisible(false);
        distance.setVisible(false);
    }//GEN-LAST:event_volActionPerformed

    private void disActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disActionPerformed
        // TODO add your handling code here:
        home.setVisible(false);
        temperatures.setVisible(false);
        volume.setVisible(false);
        masse.setVisible(false);
        distance.setVisible(true);
    }//GEN-LAST:event_disActionPerformed

    private void input_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_tActionPerformed

    private void conv_dKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_conv_dKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_conv_dKeyPressed

    private void conv_dKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_conv_dKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_conv_dKeyReleased

    private void input_vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_vActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_vActionPerformed

    private void conv_tMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conv_tMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_conv_tMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_d;
    private javax.swing.JButton back_m;
    private javax.swing.JButton back_t;
    private javax.swing.JButton back_v;
    private javax.swing.JButton clc_d;
    private javax.swing.JButton clc_m;
    private javax.swing.JButton clc_t;
    private javax.swing.JButton clc_v;
    private javax.swing.JComboBox<String> comb_d;
    private javax.swing.JComboBox<String> comb_m;
    private javax.swing.JComboBox<String> comb_t;
    private javax.swing.JComboBox<String> comb_v;
    private javax.swing.JButton conv_d;
    private javax.swing.JButton conv_m;
    private javax.swing.JButton conv_t;
    private javax.swing.JButton conv_v;
    private javax.swing.JButton dis;
    private javax.swing.JPanel distance;
    private javax.swing.JButton ex;
    private javax.swing.JButton ex_d;
    private javax.swing.JButton ex_m;
    private javax.swing.JButton ex_t;
    private javax.swing.JButton ex_v;
    private javax.swing.JPanel home;
    private javax.swing.JTextField input_d;
    private javax.swing.JTextField input_m;
    private javax.swing.JTextField input_t;
    private javax.swing.JTextField input_v;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton mas;
    private javax.swing.JPanel masse;
    private javax.swing.JTextField output_d;
    private javax.swing.JTextField output_m;
    private javax.swing.JTextField output_t;
    private javax.swing.JTextField output_v;
    private javax.swing.JPanel temperatures;
    private javax.swing.JLabel titel_d;
    private javax.swing.JLabel titel_m;
    private javax.swing.JLabel titel_t;
    private javax.swing.JLabel titel_v;
    private javax.swing.JButton tm;
    private javax.swing.JButton vol;
    private javax.swing.JPanel volume;
    // End of variables declaration//GEN-END:variables

    
}
